# Custom Language File for Launcher Customizer

[ejs.app]
title = "Fluxo Launcher"

[ejs.landing]
mediaGitHubURL = "https://discord.gg/WpvpmNjPbq"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/WpvpmNjPbq"

[ejs.settings]
sourceGithubLink = "https://discord.gg/WpvpmNjPbq"
supportLink = "https://discord.gg/WpvpmNjPbq"

[ejs.welcome]
welcomeHeader = "Bem-vindo ao Fluxo Launcher"
welcomeDescription = "Clique Jogar para começar!"
welcomeDescCTA = "Entre em nosso discord"
